CREATE SEQUENCE SEQ_STOCK_ID
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1;

CREATE TABLE TB_STOCK(
   ID NUMBER PRIMARY KEY NOT NULL,
   NAME VARCHAR(100) UNIQUE ,
   CURRENT_PRICE DECIMAL(23,2),
   CREATE_TIME TIMESTAMP,
   LAST_UPDATE TIMESTAMP
 );