spring:
  profiles:
    active: development
  datasource:
    url: jdbc:h2:mem:stocks
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    properties:
      hibernate.dialect: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true
springdoc:
  api-docs.path: "/api-docs"
  swagger-ui:
    operationsSorter: "method"
    path: "/swagger-ui"

flyway.url: ${spring.datasource.url}
flyway.user: ${spring.datasource.username}
flyway.password: ${spring.datasource.password}

server.error.path: /error